### PR TITLE
Syntax sugar:  Accessing members of returned objects

### PR DESCRIPTION
**Pull request by melex750**
**#384**
```c++
extern void object::New()
{
    goto( radar(Titanium).position );

    bool b = radar(BotFactory).busy();
}
```
**This also allows [method chaining](https://en.wikipedia.org/wiki/Method_chaining#Java):**
```c++
    AClass ac();
     " provided that each chained method returns "this"... "

    ac.SetInt(4).SetBool(true).SetFloat(3.14).SetString("str");
```
And accessing array elements if that is wanted, it can be enabled with one line of code.
object o = radarall(PowerPlant)[0]; <-- element access(currently disabled)

### CODE REVIEW

**Comment by krzys-h** [comment]
Could you please add some unit tests for this?

**Comment by melex750** [comment]
I'll add some more tests a bit later.

**Comment by krzys-h** [comment]
That's a lot more tests than I expected, thanks. We'll probably have to start splitting them into separate files soon, I'm starting to get lost in the test file already :stuck_out_tongue:

Some problems reported by colobot-lint (I should really make Jenkins run this automatically):
```
[style] [license header] /home/krzys_h/Pulpit/colobot/src/CBot/CBotInstr/CBotExprRetVar.cpp:1 File doesn't have proper license header; expected line was '/*'
[style] [license header] /home/krzys_h/Pulpit/colobot/src/CBot/CBotInstr/CBotExprRetVar.h:1 File doesn't have proper license header; expected line was '/*'
```

**Comment by melex750** [comment]
Yeah, adding more tests is probably not necessary, the current ones test the feature completely.
I wasn't sure if I should add the license header, I'll do that in a minute.
I thought I could add a few comments to the code today, but... PBKAC ...writer's block.

**Comment by melex750** [comment]
Another option to consider, is adding this after definition and "new" constructor calls.
```c++
AClass a = new AClass().WithFeatureA(1).WithFeatureB(2);
```

**Comment by krzys-h** [comment]
@melex750 I think the syntax with constructor you mentioned should be supported. Do you want to add it in this PR or should I just merge it as it is?

**Comment by melex750** [comment]
@krzys-h As is.
I think the other should be done a little differently.
Maybe methods only?

**Comment by CyborgMaster** [comment]
I would love to have the constructor chaining work.  I have several places in the code where I would like to do things like 

``` cpp
if (new Base().checkForResource())
```
or stuff like that.

**Pull request merged**
