### PR TITLE
Allow circular references from different classes

### PR DESCRIPTION
**Pull request by melex750**
Issue #433

### CODE REVIEW

**Comment by CyborgMaster** [comment]
Awesome!  I'll test this out this evening.  

@melex750, you are a wizard!

**Comment by krzys-h** [comment]
Could we get some unit tests for this too pleeeease? We should extend the test suite whenever possible.

**Comment by melex750** [comment]
If I push unit tests, will it conflict?
Only two tests. I can paste them here if that's easier.

**Comment by krzys-h** [comment]
@melex750 It shouldn't, even if it does I can fix it easily.

**Comment by CyborgMaster** [comment]
I know this was already merged, so it's a bit of a moot point, but I can confirm that the forward declaration works great!  Yay for no more commenting lines out and back in every time I launch the program.

**Pull request merged**
