### PR TITLE
#724 #156 #316 All in one

### PR DESCRIPTION
**Pull request by Smok94**
#724 Apperance changes:
1)Default color for sripes is green(0,255,0).
2)Face buttons 2 and 4 swaped.
3)Default hair colors changed to fit icons.
4)When face is changed, hair color changes to defaut for that face.

Changed:
src/common/restext.cpp (2)
src/level/player_profile.cpp (3,4)
src/level/player_profile.h (4)
src/ui/screen/screen_apperance.cpp (2,4)

#156 Firstperson for Me:
First person mode enabled for Me and technicans.
Camera button enabled for both.
Disabled robotcamera syle when in first person for humans.

Check here: http://imgur.com/R6nqtXa

Changed:
src/level/robotmain.cpp (1) - only last part of changes
src/ui/object_interface.cpp (2,3)

#316 History for comand console:
1)Added up/down arrow actions for sroling history like in operating systems terminals.
2)Maximum command lenght moved to constant, max number of slots in istory in constant
3)To history saved are only commands that worked
    So existing commads like: "selectinsect", "debugmode", etc.
    will be saved. Other random texts will dont.
4)Duplicates of previus command wont be saved
    So  "selectinsect"->"debugmode"->"selectinsect" will be saved as:
    3-"selectinsect"
    2-"debugmode"
    1-"selectinsect"
    But "selectinsect"->"selectinsect"->"debugmode"->"debugmode"->"debugmode" will be saved as:
    2-"selectinsect"
    1-"debugmode"

Changed:
src/level/robotmain.cpp (1,2,3,4)
src/level/robotmain.h (1,2,3,4)

### CODE REVIEW

**Comment by piotrdz** [comment]
Can one of the admins verify this patch?

**Comment by Erihel** [comment]
**I did not check code in this commit.**

If this PR has the same commits as https://github.com/colobot/colobot/pull/752 then maybe close the other one?

Also change all commit messages. Look maybe at https://github.com/colobot/colobot/commits/master branch. Have some description of what commit does not just ticket number that doesn't say anything unless you open github. Try to keep title short (less then 50 chars). Second line blank and from third break line at 72 chars.

Another thing is squash those commits. Make few commits where each deals with different ticket.

If you want to fix some minor issues with your previous commit you can check this for reference http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html

**Comment by Smok94** [comment]
Ok. There is to many commits to fix and I'm very new at using git. I'm going to just remake my repository.

**Comment by krzys-h** [comment]
Additionaly, please hold off on changing the stripes to green in #724. That change was not yet discussed by the team, and the issue itself didn't get the "accepted" label.

**Pull request closed without merging**
