### PR TITLE
Save screenshots using PHYSFS instead of FILE*

### PR DESCRIPTION
**Pull request by melex750**

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Doesn't `COutputStream` destructor close the stream/file? That'd make explicit `close` calls before returns redundant, as RAII should do that instead.

**Comment by melex750** [comment]
It looks like ```~COutputStream``` and superclass d-tors do not close the stream and
there are explicit ```close``` calls in many other places so maybe it was designed that way.

**Comment by CookiePLMonster** [comment]
I see, that's a shame. You'd expect a stream-like interface to do RAII properly, but looks like it's not the case.

**Comment by melex750** [comment]
Inherited data member ```COutputStream::m_buffer``` does close the stream in its d-tor,
so it probably does work as you suggested.

**Pull request merged**
