### PR TITLE
update french translation

### PR DESCRIPTION
**Pull request by mquinson**

### CODE REVIEW

**Comment by krzys-h** [comment]
@OdyX Could you review these translations?

**Comment by mquinson** [comment]
high five, @OdyX ;)

**Comment by krzys-h** [comment]
Merged these changes into `dev` branch manually because you targetted the wrong branch in the PR.
8ce8b2fff3dce8f9407d7d1966d878c8c321c7d1

**Comment by mquinson** [comment]
Whoops, sorry for this mistake, and thanks for merging.

**Pull request closed without merging**
