### PR TITLE
User friendly abort error messages

### PR DESCRIPTION
**Pull request by krzys-h**
I need somebody to confirm how portable across compilers the code in the demangle() function is

### CODE REVIEW

**Comment by krzys-h** [comment]
If you are interested in how it looks:
image

**Comment by krzys-h** [comment]
Could somebody confirm that this compiles successfully on MSVC?

**Comment by piotrdz** [comment]
Build finished successfully

**Comment by piotrdz** [comment]
^ Nice :) It was my Jenkins server impersonating me. We should probably create a bot account for that.

**Comment by krzys-h** [comment]
I was wondering how is it possible that you posted it in the same momen the build finished :grinning: (I had IRC open)

**Comment by piotrdz** [comment]
Tested with MSVC2013 - after fixing set_terminate() issue, everything works fine.

**Comment by piotrdz** [comment]
Build finished successfully

**Pull request merged**
