### PR TITLE
Right click camera

### PR DESCRIPTION
**Pull request by krzys-h**
Just found some old code in the CCamera class that does what I wanted to to for a long time ;) I wanted to test how right-click to rotate camera would work in Colobot. After some experimenting I think it's a lot easier to use and more precise than the old move cursor to the edge one. Feel free to test the dev-right-click-camera build and discuss here.
Currently works only in object back camera.

### CODE REVIEW

**Comment by krzys-h** [comment]
The next commit changes camera smoothing to be a lot faster. In my opinion this is a lot better. This applies globally, not only to camera movement (try changing objects for example).

**Comment by RaptorParkowsky** [comment]
I think it would be better to rotate camera by middle mouse button in both X and Y axis, just like in Blender or something. Then we would add right mouse button to other feature, like dolly-zooming or changing size of lens, or maybe other more common thing in gameplay itself. Optionally some of the camera features would be available only with "freecam" or other camera related cheats.

I don't know, camera smoothing was already pretty fast and elegant to me. Even effective. But I must download this build somewhere somehow when it'll be available and check this all by myself for final opinion.

**Comment by pastuh** [comment]
Adlast i can rotate camera with mouse.

But.. im still missing ability to move camera while i watch code window..
I mean.. i want to see code and model actions too ..
Camera should follow model while i watch code window :)

**Comment by krzys-h** [comment]
I'm still waiting for opinions on this

**Comment by RaptorParkowsky** [comment]
I highly prefer to using a middle mouse button and bring back an option to switch into old "cursor-to-the-edge" option as most of RTS games have both solutions. Old "cursor-to-the-edge" rotating should be turned off as default and switching it on shouldn't deactivating our new middle click camera rotating.

I'm not able to test your recent changes, especially for camera moving for known reason though :/ .

**Comment by krzys-h** [comment]
I still think right click is better than middle click. Right mouse button is easier to press and just feels more correct to me. Waiting on opinion from others. I don't see any reason why we couldn't make it accept both, Colobot doesn't use any other mouse buttons anyway.
Unfortunately current keybinding system is unable to handle mouse buttons :(

**Comment by krzys-h** [comment]
Both right and middle mouse button work now.

**Comment by tomaszkax86** [comment]
We should definitely add control option for binding to mouse. Remember we might want gamepads to support this feature as well. Primary action/selection (left mouse button) could also use binding option in the future. Also, middle mouse button could be used to move camera when nothing is selected and in CBot editor. This feature could become part of potential future in-game level editor, you could freely move and rotate camera around with mouse.

**Comment by tomangelo2** [comment]
Well, mouse is currently irreplaceable, there are issues #653 and #649 about that. Without mouse you can't aim, navigate in UI or control a camera. With these commits there will be fixed issue with camera, but aiming and UI navigating will still be available only with mouse.

**Comment by RaptorParkowsky** [comment]
@tomangelo2 With that moving around UI without a mouse (only by keyboard or gamepad) we could do something like it was in BuzzingCars EPSITEC's game. Only if we had it's source code... Otherwise we just probably wait for CEGUI implementation.

**Comment by krzys-h** [comment]
> Only if we had it's source code...

At this point of the development having the source code would be no better than reimplementing it because you would need to adjust that code to all our refactoring anyway

**Comment by RaptorParkowsky** [comment]
@krzys-h But it's the same engine like Colobot so it would be probably easy to implement and/or refactor in GOLD though.

**Comment by krzys-h** [comment]
> it would be probably easy to implement

So like I said, it would be our own reimplementation anyway, so having the original source code doesn't matter

**Comment by krzys-h** [comment]
And obviously CEGUI will be a reimplementation of the whole UI code anyway

**Comment by tomangelo2** [comment]
@RaptorParkowsky But our code is currently quite modified comparing to original Colobot, having BC source code with their modifications and trying to copy that to our code with our modifications wouldn't be so much better than just implement this once while rewriting interface to CEGUI.

**Comment by RaptorParkowsky** [comment]
Okay, finally tested this one and it works perfectly for me. I think it's worth merging with 0.1.7 release.

**Pull request merged**
