### PR TITLE
Clean CBot Interface

### PR DESCRIPTION
**Pull request by Grunaka**
I have finish to clean CBot interface.
Basically I moved each class in their own source and header files.

### CODE REVIEW

**Comment by piotrdz** [comment]
Can one of the admins verify this patch?

**Comment by krzys-h** [comment]
The fact that you should include only the CBot.h file (the public API part) and not the individual internal files should be documented somewhere

**Comment by krzys-h** [comment]
I'll test and merge this pull request today

**Comment by krzys-h** [comment]
Sorry that it took so long, I didn't have time to test it until now

**Pull request merged**
