### PR TITLE
Solves #700

### PR DESCRIPTION
**Pull request by KarolTrzeszczkowski**
It turns out, that tower is not over powered in code battle mode. It never hits flying enemy robot.

### CODE REVIEW

**Comment by piotrdz** [comment]
Can one of the admins verify this patch?

**Comment by krzys-h** [comment]
Your indentation is wrong. Use 4 spaces instead of tabs.

**Comment by krzys-h** [comment]
Could you squash these two commits now?
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by KarolTrzeszczkowski** [comment]
I don't know how to do it only with github graphical interface.

**Comment by krzys-h** [comment]
I just did this for you - 1960b373f1a3124053339e2febbc7990ef92cf7f

**Comment by KarolTrzeszczkowski** [comment]
Thanks.

**Pull request closed without merging**
