### PR TITLE
Some Gameplay & UI Improvements

### PR DESCRIPTION
**Pull request by DavivaD**
This time I will not broke it D: Sorry.

### CODE REVIEW

**Comment by krzys-h** [comment]
Please don't put multiple things in one pull request, it makes it a lot harder to discuss and review them.

The changes look good from code style perspective, but I'd like to hear some feedback from the community about each of these changes, especially the gameplay ones.

**Comment by DavivaD** [comment]
d6dabfe is extension of 656ca91

**Comment by rbcat** [comment]
> Increase OrgaShooter Damage to similar to Shooter Damage
IMHO this one isn't very sensible. Maybe it should be even greater to make orga shooters into truly cool weapons, or, better yet, just stay unchanged (their damage is very low compared to that of fireball shooters now). I personally prefer the later, because it makes more sense giving that they take less energy for shooting and it still allows fireball shooters to be a сompetitor when it comes to wars between robots.

And it looks like fire can actually do more damage than organic chemicals in real life.

**Comment by immibis** [comment]
If you want to rebalance orgashooters for code battles, perhaps they should need alien matter or something.

**Comment by MrSimbax** [comment]
I'm closing this pull request because of 2 reasons:
1) The changes should be split into separate pull requests.
2) There are conflicting files so it needs an update anyway.

**Pull request closed without merging**
