### PR TITLE
fix MacOSX install instruction and compilation after switch to SDL2

### PR DESCRIPTION
**Pull request by vieux**
@piotrdz @krzys-h this might break windows/linux, I only compile on Mac, please take a look.

### CODE REVIEW

**Comment by piotrdz** [comment]
Can one of the admins verify this patch?

**Comment by piotrdz** [comment]
@piotrdz [Jenkins]: test this please.

**Comment by krzys-h** [comment]
USE_SDL_MAIN should be also removed from CMake files if not needed anymore. I'll try compilation on Windows later.

**Comment by krzys-h** [comment]
49ee00d90d01d63fc1baaf8596d589162e839034

**Pull request closed without merging**
