### PR TITLE
New CBot syntax highlighting

### PR DESCRIPTION
**Pull request by krzys-h**
This is my proposal for new CBot syntax highlighting. Tell me if you like it or not.
image

### CODE REVIEW

**Comment by RaptorParkowsky** [comment]
I like it, but the previous hightligting used the texture parts from, well, some button#.png or other textures. I'd like to remove that texture parts if they are not used somewhere else. This would be another step to make UI textures as clean as possible and good step into CEGUI.

**Comment by krzys-h** [comment]
I believe it might have used to in the original game, but in the Gold Edition it seems to just use color values in the code. You can even see it disables texturing before rendering the text:
https://github.com/colobot/colobot/pull/575/files#diff-8a4a7a28f640852bfde25e15f022644bR836
You would probably have to ask @piotrdz, I believe he is the one who rewrote the CText for the new engine

**Comment by MrSimbax** [comment]
The font doesn't look like it's monospaced. I'd also use colors which are more distinct, contrast.

**Comment by piotrdz** [comment]
@RaptorParkowsky: CText does not use any texture files for rendering actual font characters, but it draws icons in text using texture files:
https://github.com/colobot/colobot/blob/dev/src/graphics/engine/text.cpp#L855-L877

**Comment by krzys-h** [comment]
@piotrdz Those "icons" are just buttons that are embedded in SatCom help files
@MrSimbax Yeah, the font seems to be not monospaced (again, we fixed this already at some point...). You could play around with the colors a bit and see if you can make it look beter.

**Comment by piotrdz** [comment]
[jenkins] Build finished successfully

**Comment by krzys-h** [comment]
This is how it looks with a monospaced font:
image

**Comment by krzys-h** [comment]
@MrSimbax is that better?
image

**Comment by piotrdz** [comment]
[jenkins] Build finished successfully

**Comment by krzys-h** [comment]
@piotrdz Don't you think that showing the check as finished is enough? It doesn't need to spam the comments all the time

**Comment by piotrdz** [comment]
@krzys-h: it should be disabled now.

**Comment by MrSimbax** [comment]
I meant lighter text or darker background. Ugh, it's hard to discuss really, as it's a matter of taste. Wish we could have custom themes by now :/ I think it's fairly good, you can't match everyone's personal taste anyway.

Mentions of colors in SatCom needs to be changed. They should be rephrased like "types are shown like that:" instead of "types are always written with green color".

**Comment by tomangelo2** [comment]
We could add later a tab in Options to customize the colors.
Also we should think in future for special mode for colorblind people.

**Comment by krzys-h** [comment]
image
I think this can be merged now. Any other throughts before that?

**Pull request merged**
