### PR TITLE
Don't crash when number is assigned to string

### PR DESCRIPTION
**Pull request by VictorDenisov**
Fix for issue #419

### CODE REVIEW

**Comment by krzys-h** [comment]
I don't think this is a proper way to fix that issue. By design, CBot doesn't do automatic type casting, so something like this should just NOT work and show compile error instead (and it does so in current version):
```C++
string a;
a = 0;
```
The same thing should happen when working with arrays, as described in issue #419 (and that doesn't work in current version, it just crashes the game on execution):
```C++
int[] a;
a[0] = "test";
```
This might change when we rewrite whole CBot engine, but currently I'd prefer typecasting in CBot to stay as it is right now.

**Comment by VictorDenisov** [comment]
Int to float, boolean to string, even string to float and string to int casts already exist, but these two shouldn't? How so? Is it better to crash the app instead? I just used an existing mechanism for type casts and changed order of assignments.

**Comment by krzys-h** [comment]
These casts exist, but don't happen automatically.
```C++
int a = 5.5; // ok, works
string b = true; // compiles but crashes
float c = "1.5"; // doesn't compile, invalid assigment
int d = "5"; // doesn't compile, invalid assigment
```

To convert anything to string, you have to force a cast like so:
```C++
string a = ""+true;
string b = ""+5;
string c = ""+1.5;
```
To cast a string to number, you do this:
```C++
int a = strval("5");
float b = strval("1.5");
```

**Comment by krzys-h** [comment]
These casts exist, but don't happen automatically.
```C++
int a = 5.5; // ok, works
string b = true; // compiles but crashes
float c = "1.5"; // doesn't compile, invalid assigment
int d = "5"; // doesn't compile, invalid assigment
```

To convert anything to string, you have to force a cast like so:
```C++
string a = ""+true;
string b = ""+5;
string c = ""+1.5;
```
To cast a string to number, you do this:
```C++
int a = strval("5");
float b = strval("1.5");
```

**Pull request closed without merging**
